% function configString = configuration2string(config)
%
% Get a quick string from a configuration
%
function configString = configuration2string(config)
    try
        configString =  sprintf('FeatureSelection: %d/%d Features; PreProcessing: %s; Feature Transform: %s; FTTargetDimPercent: %0.1f; FTHyperparams: %s; Classifier: %s; CLHyperparams: %s', ...
        sum(single(config.configFeatureSelection.featureSubSet)), numel(config.configFeatureSelection.featureSubSet), ...
        config.configPreprocessing.featurePreProcessingMethod, ...
        config.configFeatureTransform.featureTransformMethod, ...
        queryStruct(config.configFeatureTransform.featureTransformParams,'dimensionalityPercentage',-1),...
        struct2csv(queryStruct(config.configFeatureTransform,'featureTransformHyperparams',struct),','), ...
        config.configClassifier.classifierName, ...
        struct2csv(queryStruct(config.configClassifier,'classifierParams',struct),','));

    catch
        configString = '';
    end